### ISSUE TITLE
consider making record even more generic?

### ISSUE THREAD

**Issue by jonschlinkert** [node-task/record#1]
hey @tkellen, I'd like to propose that we "pivot" `record` so that it is a non-file-oriented, completely generic standard library (meaning more generic than it already is) that can be used as a basis for creating more specific record formats (like you've done with the `*-io` libs). 

**Why?**

Especially in light of vinyl's success as a virtual file format, going this extra step (to be more generic) will re-focus record on being a general-usage virtual record format, step out of vinyl's way, and offer node.js users a starting point for virtual records that have zero association with the file system. 

**What good is a virtual record without any "file" at all?**

Validation, normalization, standardization.  Virtual records are tactfully decorated with sensible convenience methods that allow developers to focus more on innovation and writing solid code, and less on "how to structure the object".

**What would I change?**

just thinking out loud, here are a couple of things that come to mind:
1. The record specification includes `path`, perhaps we can change `path` to something non-file related, like `key` or `id`
2. It would be nice to give implementors ways to customize the class and/or methods. Like customizing the inspect method

If you're open to any of this, I'd be happy to take a stab at updating the lib. 

thoughts?

**Comment by tkellen** [comment]
Hey @jonschlinkert! I have largely stepped away from the node task runner space. I think your idea has a ton of merit and I'd be happy to see you run with it here. I'm adding you as a owner/collaborator for this organization. I'm excited to see where you take it!

**Comment by jonschlinkert** [comment]
great, thanks @tkellen!
